import { Post, UserProfile, ExchangeProposal, Conversation, NotificationItem, ReviewItem } from '@/types/exchange';

export const media = {
  phone: '/phone.svg',
  camera: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=82',
  guitar: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=900&q=82',
  books: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=900&q=82',
  cycle: 'https://images.unsplash.com/photo-1502744688674-c619d1586c9e?auto=format&fit=crop&w=900&q=82',
  chair: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=82',
  console: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=900&q=82',
  laptop: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=82',
  priya: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80',
  arun: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80',
  kavya: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=160&q=80',
  rishi: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=160&q=80',
};

export const categories: [string, string][] = [
  ['Electronics', '⌁'],
  ['Mobile Phones', '▯'],
  ['Computers', '⌘'],
  ['Gaming', '◉'],
  ['Vehicles', '◌'],
  ['Furniture', '▰'],
  ['Fashion', '♧'],
  ['Books', '▤'],
  ['Musical Instruments', '♫'],
  ['Home & Garden', '✿'],
  ['Sports', '◒'],
  ['Collectibles', '◇'],
  ['Others', '⋯'],
];

export const initialPosts: Post[] = [
  {
    id: 'p-phone',
    owner: 'Arun',
    avatar: media.arun,
    title: 'iPhone 13',
    condition: 'Good',
    category: 'Mobile Phones',
    city: 'Chennai',
    locality: 'Anna Nagar',
    wanted: 'Mirrorless camera, gaming console, or a practical surprise.',
    description: 'Used carefully for two years. Everything works smoothly. Comes with the original cable and a protective case.',
    image: media.phone,
    time: '2h ago',
    exchanges: 12,
    rating: '4.8',
    mine: false,
    status: 'active',
  },
  {
    id: 'p-camera',
    owner: 'Kavya',
    avatar: media.kavya,
    title: 'Fujifilm X-T20 Camera',
    condition: 'Like New',
    category: 'Electronics',
    city: 'Bangalore',
    locality: 'Indiranagar',
    wanted: 'A lightweight laptop, a city bicycle, or an acoustic guitar.',
    description: 'A lovely little camera in excellent condition. Includes two batteries, strap, charger and 35mm lens.',
    image: media.camera,
    time: '4h ago',
    exchanges: 9,
    rating: '4.9',
    mine: false,
    status: 'active',
  },
  {
    id: 'p-guitar',
    owner: 'Rishi',
    avatar: media.rishi,
    title: 'Yamaha acoustic guitar',
    condition: 'Good',
    category: 'Musical Instruments',
    city: 'Kochi',
    locality: 'Panampilly Nagar',
    wanted: 'Books, a keyboard, or something creative.',
    description: 'Warm sounding acoustic guitar. Recently restrung and ready for its next home.',
    image: media.guitar,
    time: '5h ago',
    exchanges: 7,
    rating: '4.7',
    mine: false,
    status: 'active',
  },
  {
    id: 'p-books',
    owner: 'Meera',
    avatar: media.kavya,
    title: 'Collected design books',
    condition: 'Good',
    category: 'Books',
    city: 'Hyderabad',
    locality: 'Banjara Hills',
    wanted: 'Home plants, records, or a compact speaker.',
    description: 'A thoughtful collection of six visual design and architecture books.',
    image: media.books,
    time: 'Yesterday',
    exchanges: 15,
    rating: '4.8',
    mine: false,
    status: 'active',
  },
  {
    id: 'p-cycle',
    owner: 'Naveen',
    avatar: media.arun,
    title: 'City bicycle',
    condition: 'Fair',
    category: 'Vehicles',
    city: 'Pune',
    locality: 'Kothrud',
    wanted: 'Laptop stand, headphones, or a bookshelf.',
    description: 'Reliable bicycle for daily city rides. A few cosmetic marks, but rides well.',
    image: media.cycle,
    time: 'Yesterday',
    exchanges: 5,
    rating: '4.6',
    mine: false,
    status: 'active',
  },
  {
    id: 'p-console',
    owner: 'Priya',
    avatar: media.priya,
    title: 'Nintendo Switch Lite',
    condition: 'Like New',
    category: 'Gaming',
    city: 'Chennai',
    locality: 'Adyar',
    wanted: 'An instant camera, compact speaker, or useful tech.',
    description: 'Kept in a case from day one. Includes charger and game case.',
    image: media.console,
    time: 'Yesterday',
    exchanges: 6,
    rating: '4.9',
    mine: true,
    status: 'active',
  },
  {
    id: 'p-chair',
    owner: 'Aditi',
    avatar: media.kavya,
    title: 'Reading chair',
    condition: 'Good',
    category: 'Furniture',
    city: 'Mumbai',
    locality: 'Bandra',
    wanted: 'Indoor plants, a floor lamp, or storage pieces.',
    description: 'A comfortable accent chair with a soft linen cover and very small signs of use.',
    image: media.chair,
    time: '2d ago',
    exchanges: 11,
    rating: '4.8',
    mine: false,
    status: 'active',
  },
  {
    id: 'p-laptop',
    owner: 'Priya',
    avatar: media.priya,
    title: 'MacBook sleeve & stand set',
    condition: 'New',
    category: 'Computers',
    city: 'Chennai',
    locality: 'Adyar',
    wanted: 'A compact desk lamp or a good backpack.',
    description: 'Unused protective sleeve and adjustable aluminium stand.',
    image: media.laptop,
    time: '3d ago',
    exchanges: 6,
    rating: '4.9',
    mine: true,
    status: 'active',
  },
];

export const initialUser: UserProfile = {
  name: 'Priya Srinivasan',
  first: 'Priya',
  city: 'Chennai',
  locality: 'Adyar',
  avatar: media.priya,
  joined: 'March 2024',
  rating: '4.9',
  exchanges: 6,
  email: 'priya@example.com',
};

export const initialChats: Record<string, Conversation> = {
  arun: {
    name: 'Arun',
    avatar: media.arun,
    city: 'Chennai',
    post: 'iPhone 13',
    messages: [
      { mine: false, text: 'Hi Priya, is the Switch Lite still available?', time: '10:12 AM' },
      { mine: true, text: 'Hi Arun! Yes, it is. Is your iPhone 13 still open to an exchange?', time: '10:14 AM' },
      { mine: false, text: 'It is. I would be interested in the Switch and a few games.', time: '10:16 AM' },
    ],
  },
  kavya: {
    name: 'Kavya',
    avatar: media.kavya,
    city: 'Bangalore',
    post: 'Fujifilm X-T20 Camera',
    messages: [
      { mine: false, text: 'Your post caught my eye. Happy to talk through an exchange.', time: 'Yesterday' },
    ],
  },
};

export const initialProposals: ExchangeProposal[] = [
  {
    id: 'x-received',
    sender: 'Rishi',
    receiver: 'Priya',
    senderPost: 'p-guitar',
    receiverPost: 'p-console',
    message: 'Would you like to exchange these? I can meet this weekend.',
    status: 'pending',
    created: 'Today',
  },
  {
    id: 'x-accepted',
    sender: 'Priya',
    receiver: 'Kavya',
    senderPost: 'p-laptop',
    receiverPost: 'p-camera',
    message: 'I would love to exchange this set for your camera.',
    status: 'accepted',
    created: 'Yesterday',
  },
];

export const initialNotifications: NotificationItem[] = [
  { id: 1, icon: '↔', text: 'Rishi sent you an exchange proposal for your Nintendo Switch Lite.', time: '15 min ago', unread: true },
  { id: 2, icon: '✉', text: 'Arun replied to your conversation.', time: '1 hr ago', unread: true },
  { id: 3, icon: '♡', text: 'Kavya saved your post.', time: 'Yesterday', unread: false },
];

export const initialReviews: ReviewItem[] = [
  { name: 'Kavya M.', rating: 5, text: 'Thoughtful, friendly and easy to coordinate with. A lovely exchange!', time: 'June 2026' },
  { name: 'Naveen R.', rating: 5, text: 'Exactly as described. Smooth hand-off.', time: 'May 2026' },
];
